#!/bin/sh

. libtest.sh
. libgit.sh

test_require diff-highlight

export PATH="$(dirname -- "$diff_highlight_path"):$PATH"

gitconfig <<EOF
[color.diff-highlight]
  oldnormal=red bold
  oldhighlight=red bold 52
  newnormal=green bold
  newhighlight=green bold 22
EOF

tigrc <<EOF
set diff-highlight = true
EOF

steps '
	:save-display diff-wdiff-highlight-with-custom-colors.screen
'

in_work_dir create_repo_from_tgz "$base_dir/files/scala-js-benchmarks.tgz"

test_tig show master~4 --word-diff=plain

assert_equals 'diff-wdiff-highlight-with-custom-colors.screen' <<EOF
commit 4a68cf3c338f5724d838c3b6e5d989d5fd1c1150
Author:     Jonas Fonseca <jonas.fonseca@gmail.com>
AuthorDate: Thu Jan 16 17:39:49 2014 -0500
Commit:     Jonas Fonseca <jonas.fonseca@gmail.com>
CommitDate: Thu Jan 16 17:39:49 2014 -0500
 
    Integrate app code into the benchmark infrastructure
---
 common/Benchmark.scala        | 19 +++++++++++++++----
 common/BenchmarkApp.scala     | 47 +++++++++++++++++++++++++++++++++++++++++++++++
 common/DOMTypes.scala         | 49 +++++++++++++++++++++++++++++++++++++++++++++++++
 common/reference/deltablue.js |  7 +++----
 common/reference/richards.js  |  6 +++---
 common/reference/tracer.js    |  6 +++---
 common/start-benchmark.js     |  4 +---
 tracer/App.scala              | 28 +++++++---------------------
 tracer/Engine.scala           |  1 +
 tracer/JSTypes.scala          | 49 -------------------------------------------------
 tracer/RenderScene.scala      |  2 ++
 tracer/Tracer.scala           |  2 +-
 tracer/exports.js             |  9 +--------
 tracer/index-dev.html         |  4 ++--
 tracer/index.html             |  4 ++--
 15 files changed, 137 insertions(+), 100 deletions(-)
 
diff --git a/common/Benchmark.scala b/common/Benchmark.scala
index a970c83..a1c320e 100644
--- a/common/Benchmark.scala
+++ b/common/Benchmark.scala
@@ -12,16 +12,27 @@ import scala.compat.Platform
import scala.scalajs.js
 
object Benchmark {
  val benchmarks = [-js.Array[js.Function0[Unit]]()-]{+js.Array[Benchmark]()+}
{+  val benchmarkApps = js.Array[BenchmarkApp]()+}
 
  val global = js.Dynamic.global.asInstanceOf[js.Dictionary]
  [-global("ScalaJSBenchmarks")-]{+global("runScalaJSBenchmarks")+} = [-benchmarks-]{+runBenchmarks _+}
{+  global("initScalaJSBenchmarkApps") = initBenchmarkApps _+}
 
  def add(benchmark: Benchmark) {
    [-benchmarks.push-]{+benchmarks.push(benchmark)+}
{+    if (benchmark.isInstanceOf[BenchmarkApp])+} {
      [-benchmark.report _-]{+benchmarkApps.push(benchmark.asInstanceOf[BenchmarkApp])+}
[diff] 4a68cf3c338f5724d838c3b6e5d989d5fd1c1150 - line 1 of 407                                                                                                                           10%
EOF
